version: "2"

# IMPORTANT NOTE: Volume paths mounted on containers are relative to the directory that
# this file is in (`docker/`) and so probably need to start with `../` to refer to a
# directory in the main code checkout

volumes:
  dbvolume:
  rabbitmq:

services:

  db:
    image: postgres:9.5.3
    volumes:
      - ./dbvolume:/var/lib/postgresql/data/
    ports:
      - "15432:5432"

  redis:
    image: redis:3.2.1
    volumes:
      - ./docker/data/redis:/data

  rabbitmq:
    image: rabbitmq:3.6.5
    volumes:
      - rabbitmq:/var/lib/rabbitmq:z

  web:
    build:
      context: ..
      dockerfile: Dockerfile
    command: python3 /code/messybrainz/manage.py runserver -h 0.0.0.0 -p 8080 -d
    image: web
    volumes:
      - ..:/code/messybrainz
    ports:
      - "8080:8080"
    depends_on:
      - db
      - musicbrainz_db
      - redis
      - rabbitmq

  musicbrainz_db:
    image: metabrainz/musicbrainz-test-database:schema-change-2017-q2
    volumes:
      - ../data/mbdata:/var/lib/postgresql/data/pgdata
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      MB_IMPORT_DUMPS: "true"
    ports:
      - "5430:5432"

  cluster:
    image: web
    command: python3 -m "messybrainz.cluster.cluster"
    volumes:
      - ..:/code/listenbrainz:z
    depends_on:
      - db
      - rabbitmq
